from . import db
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    fullName = db.Column(db.String(150))
    username = db.Column(db.String(150))
    email = db.Column(db.String(150), unique=True)
    emailauth = db.Column(db.String(150)) # Used to verify email address using autogenerated number
    password = db.Column(db.String(150))

class Counter(db.Model):
    id = db.Column(db.Integer, primary_key=True)
